name: Check for new ETLegacy x86_64 Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: write         # Grants permission to push changes

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y curl && sudo snap install htmlq

      - name: Fetch ETLegacy webpage
        run: curl -s https://www.etlegacy.com/workflow-files > page.html

      - name: Extract latest x86_64 build URL
        id: extract_url
        run: |
          # Extract the x86_64 .tar.gz link using htmlq
          FILE_URL=$(cat page.html | htmlq --attribute href a | grep 'x86_64.tar.gz' | head -n 1)
          echo "File URL: $FILE_URL"
          echo "file_url=$FILE_URL" >> $GITHUB_OUTPUT

      - name: Extract build version and file name
        id: extract_version
        run: |
          FILE_URL="${{ steps.extract_url.outputs.file_url }}"
          FILE_NAME=$(basename "$FILE_URL")
          VERSION=$(echo $FILE_NAME | sed 's/.*-\(.*\)-x86_64.tar.gz/\1/')
          echo "File name: $FILE_NAME"
          echo "Version: $VERSION"
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if build already exists
        id: check_existing
        run: |
          FILE_NAME="${{ steps.extract_version.outputs.file_name }}"
          if [ -f "./builds/$FILE_NAME" ]; then
            echo "Build already exists, skipping."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Build does not exist, downloading."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Download new build
        if: steps.check_existing.outputs.exists == 'false'
        run: |
          curl -L ${{ steps.extract_url.outputs.file_url }} -o builds/${{ steps.extract_version.outputs.file_name }}

      - name: Commit new build
        if: steps.check_existing.outputs.exists == 'false'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add builds/${{ steps.extract_version.outputs.file_name }}
          git commit -m "New build ${{ steps.extract_version.outputs.version }}"
          git push